package color

import (
	"errors"
	"math"

	colorful "github.com/lucasb-eyer/go-colorful"
)

var colorMap map[string]colorful.Color
var clusterMap map[string]colorful.Color

func init() {
	colorMap = make(map[string]colorful.Color, len(colors))

	for name, color := range colors {
		colorMap[name], _ = colorful.Hex(color)
	}

	clusterMap = make(map[string]colorful.Color)

	for name, color := range clusters {
		clusterMap[name], _ = colorful.Hex(color)
	}
}

func Find(name string) (string, error) {
	if result, ok := clusters[name]; ok {
		return result, nil
	}

	return "", errors.New("color not found")
}

// Cluster resolves the closest "cluster" or bucket of colors
// For example, "rose" would map to "red" or "sky blue" would map to "blue"
// This is useful for generalizing about what basic color a particular hue
// may be, especially for faceting.
func Cluster(input colorful.Color) (string, float64) {
	closest := ""
	distance := 999999.0

	for name, color := range clusterMap {
		d := input.DistanceCIE94(color)
		distance = math.Min(d, distance)
		if d != distance {
			closest = name
		}
	}

	return closest, distance
}

// Match the input against the closest known color
func Match(input colorful.Color) (string, float64) {
	closest := ""
	distance := 999999.0

	for name, color := range colorMap {
		d := input.DistanceLab(color)
		if d < distance {
			closest = name
			distance = d
		}
	}

	return closest, distance
}

// List of common color names that we can use to cluster together hues
var clusters = map[string]string{
	"beige":     "#f5f5dc",
	"black":     "#000000",
	"blue":      "#0000ff",
	"brown":     "#8b4513",
	"gold":      "#ffd700",
	"gray":      "#808080",
	"green":     "#008000",
	"navy":      "#000080",
	"off-white": "#f5f5f5",
	"orange":    "#ffa500",
	"pink":      "#ffc0cb",
	"purple":    "#800080",
	"red":       "#ff0000",
	"silver":    "#c0c0c0",
	"white":     "#ffffff",
	"yellow":    "#ffff00",
}

// List of known color names to hex values. Feel free to add to this list.
var colors = map[string]string{
	"black":                         "#000000",
	"navy":                          "#000080",
	"darkblue":                      "#00008b",
	"mediumblue":                    "#0000cd",
	"blue":                          "#0000ff",
	"darkgreen":                     "#006400",
	"green":                         "#008000",
	"teal":                          "#008080",
	"darkcyan":                      "#008b8b",
	"deepskyblue":                   "#00bfff",
	"darkturquoise":                 "#00ced1",
	"mediumspringgreen":             "#00fa9a",
	"lime":                          "#00ff00",
	"springgreen":                   "#00ff7f",
	"cyan":                          "#00ffff",
	"midnightblue":                  "#191970",
	"dodgerblue":                    "#1e90ff",
	"lightseagreen":                 "#20b2aa",
	"forestgreen":                   "#228b22",
	"seagreen":                      "#2e8b57",
	"darkslategray":                 "#2f4f4f",
	"limegreen":                     "#32cd32",
	"mediumseagreen":                "#3cb371",
	"turquoise":                     "#40e0d0",
	"royalblue":                     "#4169e1",
	"steelblue":                     "#4682b4",
	"darkslateblue":                 "#483d8b",
	"mediumturquoise":               "#48d1cc",
	"indigo":                        "#4b0082",
	"darkolivegreen":                "#556b2f",
	"cadetblue":                     "#5f9ea0",
	"cornflowerblue":                "#6495ed",
	"mediumaquamarine":              "#66cdaa",
	"dimgray":                       "#696969",
	"slateblue":                     "#6a5acd",
	"olivedrab":                     "#6b8e23",
	"slategray":                     "#708090",
	"lightslategray":                "#778899",
	"mediumslateblue":               "#7b68ee",
	"lawngreen":                     "#7cfc00",
	"chartreuse":                    "#7fff00",
	"aquamarine":                    "#7fffd4",
	"maroon":                        "#800000",
	"purple":                        "#800080",
	"olive":                         "#808000",
	"gray":                          "#808080",
	"skyblue":                       "#87ceeb",
	"lightskyblue":                  "#87cefa",
	"blueviolet":                    "#8a2be2",
	"darkred":                       "#8b0000",
	"darkmagenta":                   "#8b008b",
	"saddlebrown":                   "#8b4513",
	"darkseagreen":                  "#8fbc8f",
	"lightgreen":                    "#90ee90",
	"mediumpurple":                  "#9370db",
	"darkviolet":                    "#9400d3",
	"palegreen":                     "#98fb98",
	"darkorchid":                    "#9932cc",
	"yellowgreen":                   "#9acd32",
	"sienna":                        "#a0522d",
	"brown":                         "#a52a2a",
	"darkgray":                      "#a9a9a9",
	"lightblue":                     "#add8e6",
	"greenyellow":                   "#adff2f",
	"paleturquoise":                 "#afeeee",
	"lightsteelblue":                "#b0c4de",
	"powderblue":                    "#b0e0e6",
	"firebrick":                     "#b22222",
	"darkgoldenrod":                 "#b8860b",
	"mediumorchid":                  "#ba55d3",
	"rosybrown":                     "#bc8f8f",
	"darkkhaki":                     "#bdb76b",
	"silver":                        "#c0c0c0",
	"mediumvioletred":               "#c71585",
	"peru":                          "#cd853f",
	"chocolate":                     "#d2691e",
	"tan":                           "#d2b48c",
	"lightgrey":                     "#d3d3d3",
	"thistle":                       "#d8bfd8",
	"orchid":                        "#da70d6",
	"goldenrod":                     "#daa520",
	"palevioletred":                 "#db7093",
	"crimson":                       "#dc143c",
	"gainsboro":                     "#dcdcdc",
	"plum":                          "#dda0dd",
	"burlywood":                     "#deb887",
	"lightcyan":                     "#e0ffff",
	"lavender":                      "#e6e6fa",
	"darksalmon":                    "#e9967a",
	"violet":                        "#ee82ee",
	"palegoldenrod":                 "#eee8aa",
	"lightcoral":                    "#f08080",
	"khaki":                         "#f0e68c",
	"aliceblue":                     "#f0f8ff",
	"honeydew":                      "#f0fff0",
	"azure":                         "#f0ffff",
	"sandybrown":                    "#f4a460",
	"wheat":                         "#f5deb3",
	"beige":                         "#f5f5dc",
	"whitesmoke":                    "#f5f5f5",
	"mintcream":                     "#f5fffa",
	"ghostwhite":                    "#f8f8ff",
	"salmon":                        "#fa8072",
	"antiquewhite":                  "#faebd7",
	"linen":                         "#faf0e6",
	"lightgoldenrodyellow":          "#fafad2",
	"oldlace":                       "#fdf5e6",
	"red":                           "#ff0000",
	"magenta":                       "#ff00ff",
	"deeppink":                      "#ff1493",
	"orangered":                     "#ff4500",
	"tomato":                        "#ff6347",
	"hotpink":                       "#ff69b4",
	"coral":                         "#ff7f50",
	"darkorange":                    "#ff8c00",
	"lightsalmon":                   "#ffa07a",
	"orange":                        "#ffa500",
	"lightpink":                     "#ffb6c1",
	"pink":                          "#ffc0cb",
	"gold":                          "#ffd700",
	"peachpuff":                     "#ffdab9",
	"navajowhite":                   "#ffdead",
	"moccasin":                      "#ffe4b5",
	"bisque":                        "#ffe4c4",
	"mistyrose":                     "#ffe4e1",
	"blanchedalmond":                "#ffebcd",
	"papayawhip":                    "#ffefd5",
	"lavenderblush":                 "#fff0f5",
	"seashell":                      "#fff5ee",
	"cornsilk":                      "#fff8dc",
	"lemonchiffon":                  "#fffacd",
	"floralwhite":                   "#fffaf0",
	"snow":                          "#fffafa",
	"yellow":                        "#ffff00",
	"lightyellow":                   "#ffffe0",
	"ivory":                         "#fffff0",
	"white":                         "#ffffff",
	"air force blue":                "#5d8aa8",
	"alice blue":                    "#f0f8ff",
	"alizarin crimson":              "#e32636",
	"almond":                        "#efdecd",
	"amaranth":                      "#e52b50",
	"amber":                         "#ffbf00",
	"american rose":                 "#ff033e",
	"amethyst":                      "#9966cc",
	"android green":                 "#a4c639",
	"anti flash white":              "#f2f3f4",
	"antique brass":                 "#cd9575",
	"antique fuchsia":               "#915c83",
	"antique white":                 "#faebd7",
	"ao":                            "#008000",
	"apple green":                   "#8db600",
	"apricot":                       "#fbceb1",
	"aqua":                          "#00ffff",
	"army green":                    "#4b5320",
	"arsenic":                       "#3b444b",
	"arylide yellow":                "#e9d66b",
	"ash gray":                      "#b2beb5",
	"asparagus":                     "#87a96b",
	"atomic tangerine":              "#ff9966",
	"auburn":                        "#a52a2a",
	"aureolin":                      "#fdee00",
	"aurometalsaurus":               "#6e7f80",
	"awesome":                       "#ff2052",
	"azure mist":                    "#f0ffff",
	"baby blue":                     "#89cff0",
	"baby blue eyes":                "#a1caf1",
	"baby pink":                     "#f4c2c2",
	"ball blue":                     "#21abcd",
	"banana mania":                  "#fae7b5",
	"banana yellow":                 "#ffe135",
	"battleship gray":               "#848482",
	"bazaar":                        "#98777b",
	"beau blue":                     "#bcd4e6",
	"beaver":                        "#9f8170",
	"bistre":                        "#3d2b1f",
	"bittersweet":                   "#fe6f5e",
	"blanched almond":               "#ffebcd",
	"bleu de france":                "#318ce7",
	"blizzard blue":                 "#ace5ee",
	"blond":                         "#faf0be",
	"blue bell":                     "#a2a2d0",
	"blue gray":                     "#6699cc",
	"blue green":                    "#00dddd",
	"blue violet":                   "#8a2be2",
	"blush":                         "#de5d83",
	"bole":                          "#79443b",
	"bondi blue":                    "#0095b6",
	"boston university red":         "#cc0000",
	"brandeis blue":                 "#0070ff",
	"brass":                         "#b5a642",
	"brick red":                     "#cb4154",
	"bright cerulean":               "#1dacd6",
	"bright green":                  "#66ff00",
	"bright lavender":               "#bf94e4",
	"bright maroon":                 "#c32148",
	"bright pink":                   "#ff007f",
	"bright turquoise":              "#08e8de",
	"bright ube":                    "#d19fe8",
	"brilliant lavender":            "#f4bbff",
	"brilliant rose":                "#ff55a3",
	"brink pink":                    "#fb607f",
	"british racing green":          "#004225",
	"bronze":                        "#cd7f32",
	"bubble gum":                    "#ffc1cc",
	"bubbles":                       "#e7feff",
	"buff":                          "#f0dc82",
	"bulgarian rose":                "#480607",
	"burgundy":                      "#800020",
	"burnt orange":                  "#cc5500",
	"burnt sienna":                  "#e97451",
	"burnt umber":                   "#8a3324",
	"byzantine":                     "#bd33a4",
	"byzantium":                     "#702963",
	"cadet":                         "#536872",
	"cadet blue":                    "#5f9ea0",
	"cadet gray":                    "#91a3b0",
	"cadmium green":                 "#006b3c",
	"cadmium orange":                "#ed872d",
	"cadmium red":                   "#e30022",
	"cadmium yellow":                "#fff600",
	"cal poly pomona green":         "#1e4d2b",
	"cambridge blue":                "#a3c1ad",
	"camel":                         "#c19a6b",
	"camouflage green":              "#78866b",
	"canary yellow":                 "#ffef00",
	"candy apple red":               "#ff0800",
	"candy pink":                    "#e4717a",
	"capri":                         "#00bfff",
	"caput mortuum":                 "#592720",
	"cardinal":                      "#c41e3a",
	"caribbean green":               "#00cc99",
	"carmine":                       "#960018",
	"carmine pink":                  "#eb4c42",
	"carmine red":                   "#ff0038",
	"carnation pink":                "#ffa6c9",
	"carnelian":                     "#b31b1b",
	"carolina blue":                 "#99badd",
	"carrot orange":                 "#ed9121",
	"ceil":                          "#92a1cf",
	"celadon":                       "#ace1af",
	"celestial blue":                "#4997d0",
	"cerise":                        "#de3163",
	"cerise pink":                   "#ec3b83",
	"cerulean":                      "#007ba7",
	"cerulean blue":                 "#2a52be",
	"cg blue":                       "#007aa5",
	"cg red":                        "#e03c31",
	"chamoisee":                     "#a0785a",
	"champagne":                     "#f7e7ce",
	"charcoal":                      "#36454f",
	"cherry blossom pink":           "#ffb7c5",
	"chestnut":                      "#cd5c5c",
	"chrome yellow":                 "#ffa700",
	"cinereous":                     "#98817b",
	"cinnabar":                      "#e34234",
	"cinnamon":                      "#d2691e",
	"citrine":                       "#e4d00a",
	"classic rose":                  "#fbcce7",
	"cobalt":                        "#0047ab",
	"coffee":                        "#c86428",
	"columbia blue":                 "#9bddff",
	"cool black":                    "#002e63",
	"cool gray":                     "#8c92ac",
	"copper":                        "#b87333",
	"copper rose":                   "#996666",
	"coquelicot":                    "#ff3800",
	"coral pink":                    "#f88379",
	"coral red":                     "#ff4040",
	"cordovan":                      "#893f45",
	"corn":                          "#fbec5d",
	"cornflower blue":               "#6495ed",
	"cosmic latte":                  "#fff8e7",
	"cotton candy":                  "#ffbcd9",
	"cream":                         "#fffdd0",
	"crimson glory":                 "#be0032",
	"daffodil":                      "#ffff31",
	"dandelion":                     "#f0e130",
	"dark blue":                     "#00008b",
	"dark brown":                    "#654321",
	"dark byzantium":                "#5d3954",
	"dark candy apple red":          "#a40000",
	"dark cerulean":                 "#08457e",
	"dark champagne":                "#c2b280",
	"dark chestnut":                 "#986960",
	"dark coral":                    "#cd5b45",
	"dark cyan":                     "#008b8b",
	"dark electric blue":            "#536878",
	"dark goldenrod":                "#b8860b",
	"dark gray":                     "#a9a9a9",
	"dark green":                    "#013220",
	"dark jungle green":             "#1a2421",
	"dark khaki":                    "#bdb76b",
	"dark lava":                     "#483c32",
	"dark lavender":                 "#734f96",
	"dark magenta":                  "#8b008b",
	"dark midnight blue":            "#003366",
	"dark olive green":              "#556b2f",
	"dark orange":                   "#ff8c00",
	"dark orchid":                   "#9932cc",
	"dark pastel blue":              "#779ecb",
	"dark pastel green":             "#03c03c",
	"dark pastel purple":            "#966fd6",
	"dark pastel red":               "#c23b22",
	"dark pink":                     "#e75480",
	"dark powder blue":              "#003399",
	"dark raspberry":                "#872657",
	"dark red":                      "#8b0000",
	"dark salmon":                   "#e9967a",
	"dark scarlet":                  "#560319",
	"dark sea green":                "#8fbc8f",
	"dark sienna":                   "#3c1414",
	"dark slate blue":               "#483d8b",
	"dark slate gray":               "#2f4f4f",
	"dark spring green":             "#177245",
	"dark tan":                      "#918151",
	"dark tangerine":                "#ffa812",
	"dark terra cotta":              "#cc4e5c",
	"dark turquoise":                "#00ced1",
	"dark violet":                   "#9400d3",
	"dartmouth green":               "#00693e",
	"davy's gray":                   "#555555",
	"debian red":                    "#d70a53",
	"deep carmine":                  "#a9203e",
	"deep carmine pink":             "#ef3038",
	"deep carrot orange":            "#e9692c",
	"deep cerise":                   "#da3287",
	"deep champagne":                "#fad6a5",
	"deep chestnut":                 "#b94e48",
	"deep fuchsia":                  "#c154c1",
	"deep jungle green":             "#004b49",
	"deep lilac":                    "#9955bb",
	"deep magenta":                  "#cc00cc",
	"deep peach":                    "#ffcba4",
	"deep pink":                     "#ff1493",
	"deep saffron":                  "#ff9933",
	"denim":                         "#1560bd",
	"desert sand":                   "#edc9af",
	"dim gray":                      "#696969",
	"dodger blue":                   "#1e90ff",
	"dogwood rose":                  "#d71868",
	"dollar bill":                   "#85bb65",
	"drab":                          "#967117",
	"duke blue":                     "#00009c",
	"earth yellow":                  "#e1a95f",
	"eggplant":                      "#614051",
	"eggshell":                      "#f0ead6",
	"egyptian blue":                 "#1034a6",
	"electric blue":                 "#7df9ff",
	"electric crimson":              "#ff003f",
	"electric green":                "#00fe00",
	"electric indigo":               "#6f00ff",
	"electric lime":                 "#ccff00",
	"electric purple":               "#bf00ff",
	"electric ultramarine":          "#3f00ff",
	"electric violet":               "#8f00ff",
	"electric yellow":               "#fffe00",
	"emerald":                       "#50c878",
	"eton blue":                     "#96c8a2",
	"falu red":                      "#801818",
	"fandango":                      "#b53389",
	"fashion fuchsia":               "#f400a1",
	"fawn":                          "#e5aa70",
	"feldgrau":                      "#4d5d53",
	"fern green":                    "#4f7942",
	"ferrari red":                   "#ff2800",
	"field drab":                    "#6c541e",
	"fire engine red":               "#ce2029",
	"flame":                         "#e25822",
	"flamingo pink":                 "#fc8eac",
	"flavescent":                    "#f7e98e",
	"flax":                          "#eedc82",
	"floral white":                  "#fffaf0",
	"folly":                         "#ff004f",
	"forest green":                  "#014421",
	"french beige":                  "#a67b5b",
	"french blue":                   "#0072bb",
	"french lilac":                  "#86608e",
	"french rose":                   "#f64a8a",
	"fuchsia":                       "#ff00ff",
	"fuchsia pink":                  "#ff77ff",
	"fulvous":                       "#e48400",
	"fuzzy wuzzy":                   "#cc6666",
	"gamboge":                       "#e49b0f",
	"ghost white":                   "#f8f8ff",
	"ginger":                        "#b06500",
	"glaucous":                      "#6082b6",
	"golden brown":                  "#996515",
	"golden poppy":                  "#fcc200",
	"golden yellow":                 "#ffdf00",
	"granny smith apple":            "#a8e4a0",
	"gray asparagus":                "#465945",
	"green yellow":                  "#adff2f",
	"grullo":                        "#a99a86",
	"guppie green":                  "#00ff7f",
	"halaya ube":                    "#663854",
	"han blue":                      "#446ccf",
	"han purple":                    "#5218fa",
	"harlequin":                     "#3fff00",
	"harvard crimson":               "#c90016",
	"harvest gold":                  "#da9100",
	"heliotrope":                    "#df73ff",
	"hooker's green":                "#007000",
	"hot magenta":                   "#ff1dce",
	"hot pink":                      "#ff69b4",
	"hunter green":                  "#355e3b",
	"iceberg":                       "#71a6d2",
	"icterine":                      "#fcf75e",
	"inchworm":                      "#b2ec5d",
	"india green":                   "#138808",
	"indian yellow":                 "#e3a857",
	"international klein blue":      "#002fa7",
	"international orange":          "#ff4f00",
	"iris":                          "#5a4fcf",
	"isabelline":                    "#f4f0ec",
	"islamic green":                 "#009000",
	"jade":                          "#00a86b",
	"jasmine":                       "#f8de7e",
	"jasper":                        "#d73b3e",
	"jazzberry jam":                 "#a50b5e",
	"jonquil":                       "#fada5e",
	"june bud":                      "#bdda57",
	"jungle green":                  "#29ab87",
	"kelly green":                   "#4cbb17",
	"ku crimson":                    "#e8000d",
	"languid lavender":              "#d6cadd",
	"lapis lazuli":                  "#26619c",
	"la salle green":                "#087830",
	"laser lemon":                   "#fefe22",
	"lava":                          "#cf1020",
	"lavender blue":                 "#ccccff",
	"lavender blush":                "#fff0f5",
	"lavender gray":                 "#c4c3d0",
	"lavender indigo":               "#9457eb",
	"lavender magenta":              "#ee82ee",
	"lavender mist":                 "#e6e6fa",
	"lavender pink":                 "#fbaed2",
	"lavender purple":               "#967bb6",
	"lavender rose":                 "#fba0e3",
	"lawn green":                    "#7cfc00",
	"lemon":                         "#fff700",
	"lemon chiffon":                 "#fffacd",
	"light apricot":                 "#fdd5b1",
	"light blue":                    "#add8e6",
	"light brown":                   "#b5651d",
	"light carmine pink":            "#e66771",
	"light coral":                   "#f08080",
	"light cornflower blue":         "#93ccea",
	"light crimson":                 "#f56991",
	"light cyan":                    "#e0ffff",
	"light fuchsia pink":            "#f984ef",
	"light goldenrod yellow":        "#fafad2",
	"light gray":                    "#d3d3d3",
	"light green":                   "#90ee90",
	"light khaki":                   "#f0e68c",
	"light mauve":                   "#dcd0ff",
	"light pastel purple":           "#b19cd9",
	"light pink":                    "#ffb6c1",
	"light salmon":                  "#ffa07a",
	"light salmon pink":             "#ff9999",
	"light sea green":               "#20b2aa",
	"light sky blue":                "#87cefa",
	"light slate gray":              "#778899",
	"light taupe":                   "#b38b6d",
	"light thulian pink":            "#e68fac",
	"light yellow":                  "#ffffed",
	"lilac":                         "#c8a2c8",
	"lime green":                    "#32cd32",
	"lincoln green":                 "#195905",
	"liver":                         "#534b4f",
	"lust":                          "#e62020",
	"magic mint":                    "#aaf0d1",
	"magnolia":                      "#f8f4ff",
	"mahogany":                      "#c04000",
	"majorelle blue":                "#6050dc",
	"malachite":                     "#0bda51",
	"manatee":                       "#979aaa",
	"mango tango":                   "#ff8243",
	"mauve":                         "#e0b0ff",
	"mauvelous":                     "#ef98aa",
	"mauve taupe":                   "#915f6d",
	"maya blue":                     "#73c2fb",
	"meat brown":                    "#e5b73b",
	"medium aquamarine":             "#66ddaa",
	"medium blue":                   "#0000cd",
	"medium candy apple red":        "#e2062c",
	"medium carmine":                "#af4035",
	"medium champagne":              "#f3e5ab",
	"medium electric blue":          "#035096",
	"medium jungle green":           "#1c352d",
	"medium lavender magenta":       "#dda0dd",
	"medium orchid":                 "#ba55d3",
	"medium persian blue":           "#0067a5",
	"medium purple":                 "#9370db",
	"medium red violet":             "#bb3385",
	"medium sea green":              "#3cb371",
	"medium slate blue":             "#7b68ee",
	"medium spring bud":             "#c9dc87",
	"medium spring green":           "#00fa9a",
	"medium taupe":                  "#674c47",
	"medium teal blue":              "#0054b4",
	"medium turquoise":              "#48d1cc",
	"medium violet red":             "#c71585",
	"melon":                         "#fdbcb4",
	"midnight blue":                 "#191970",
	"midnight green":                "#004953",
	"mikado yellow":                 "#ffc40c",
	"mint":                          "#3eb489",
	"mint cream":                    "#f5fffa",
	"mint green":                    "#98ff98",
	"misty rose":                    "#ffe4e1",
	"moonstone blue":                "#73a9c2",
	"mordant red 19":                "#ae0c00",
	"moss green":                    "#addfad",
	"mountain meadow":               "#30ba8f",
	"mountbatten pink":              "#997a8d",
	"msu green":                     "#18453b",
	"mulberry":                      "#c54b8c",
	"mustard":                       "#ffdb58",
	"myrtle":                        "#21421e",
	"nadeshiko pink":                "#f6adc6",
	"napier green":                  "#2a8000",
	"navajo white":                  "#ffdead",
	"neon carrot":                   "#ffa343",
	"neon fuchsia":                  "#fe59c2",
	"neon green":                    "#39ff14",
	"non photo blue":                "#a4dded",
	"ocean boat blue":               "#0077be",
	"ochre":                         "#cc7722",
	"old gold":                      "#cfb53b",
	"old lace":                      "#fdf5e6",
	"old lavender":                  "#796878",
	"old mauve":                     "#673147",
	"old rose":                      "#c08081",
	"olive drab":                    "#6b8e23",
	"olive drab 7":                  "#3c341f",
	"olivine":                       "#9ab973",
	"onyx":                          "#0f0f0f",
	"opera mauve":                   "#b784a7",
	"orange peel":                   "#ff9f00",
	"orange red":                    "#ff4500",
	"ou crimson red":                "#990000",
	"outer space":                   "#414a4c",
	"outrageous orange":             "#ff6e4a",
	"oxford blue":                   "#002147",
	"pakistan green":                "#006600",
	"palatinate blue":               "#273be2",
	"palatinate purple":             "#682860",
	"pale blue":                     "#afeeee",
	"pale brown":                    "#987654",
	"pale cerulean":                 "#9bc4e2",
	"pale chestnut":                 "#ddadaf",
	"pale copper":                   "#da8a67",
	"pale cornflower blue":          "#abcdef",
	"pale gold":                     "#e6be8a",
	"pale goldenrod":                "#eee8aa",
	"pale green":                    "#98fb98",
	"pale magenta":                  "#f984e5",
	"pale pink":                     "#fadadd",
	"pale red violet":               "#db7093",
	"pale robin egg blue":           "#96ded1",
	"pale silver":                   "#c9c0bb",
	"pale spring bud":               "#ecebbd",
	"pale taupe":                    "#bc987e",
	"pansy purple":                  "#78184a",
	"papaya whip":                   "#ffefd5",
	"pastel blue":                   "#aec6cf",
	"pastel brown":                  "#836953",
	"pastel gray":                   "#cfcfc4",
	"pastel green":                  "#77dd77",
	"pastel magenta":                "#f49ac2",
	"pastel orange":                 "#ffb347",
	"pastel pink":                   "#ffd1dc",
	"pastel purple":                 "#b39eb5",
	"pastel red":                    "#ff6961",
	"pastel violet":                 "#cb99c9",
	"pastel yellow":                 "#fdfd96",
	"patriarch":                     "#800080",
	"payne's gray":                  "#40404f",
	"peach":                         "#ffe5b4",
	"peach orange":                  "#ffcc99",
	"peach puff":                    "#ffdab9",
	"peach yellow":                  "#fadfad",
	"pear":                          "#d1e231",
	"pearl aqua":                    "#88d8c0",
	"peridot":                       "#e6e200",
	"persian blue":                  "#1c39bb",
	"persian green":                 "#00a693",
	"persian indigo":                "#32127a",
	"persian orange":                "#d99058",
	"persian pink":                  "#f77fbe",
	"persian plum":                  "#701c1c",
	"persian red":                   "#cc3333",
	"persian rose":                  "#fe28a2",
	"persimmon":                     "#ec5800",
	"phlox":                         "#df00ff",
	"phthalo blue":                  "#000f89",
	"phthalo green":                 "#123524",
	"piggy pink":                    "#fddde6",
	"pine green":                    "#01796f",
	"pink pearl":                    "#e7accf",
	"pink sherbet":                  "#f78fa7",
	"pistachio":                     "#93c572",
	"platinum":                      "#e5e4e2",
	"portland orange":               "#ff5a36",
	"powder blue":                   "#b0e0e6",
	"princeton orange":              "#ff8f00",
	"prussian blue":                 "#003153",
	"puce":                          "#cc8899",
	"pumpkin":                       "#ff7518",
	"purple heart":                  "#69359c",
	"purple mountain majesty":       "#9678b6",
	"purple pizzazz":                "#fe4eda",
	"purple taupe":                  "#50404d",
	"quartz":                        "#51484f",
	"radical red":                   "#ff355e",
	"raspberry":                     "#e30b5d",
	"raspberry pink":                "#e25098",
	"raspberry rose":                "#b3446c",
	"raw umber":                     "#826644",
	"razzle dazzle rose":            "#ff33cc",
	"razzmatazz":                    "#e3256b",
	"redwood":                       "#ab4e52",
	"regalia":                       "#522d80",
	"rich black":                    "#004040",
	"rich brilliant lavender":       "#f1a7fe",
	"rich carmine":                  "#d70040",
	"rich electric blue":            "#0892d0",
	"rich lavender":                 "#a76bcf",
	"rich lilac":                    "#b666d2",
	"rich maroon":                   "#b03060",
	"rifle green":                   "#414833",
	"robin egg blue":                "#00cccc",
	"rose bonbon":                   "#f9429e",
	"rose ebony":                    "#674846",
	"rose gold":                     "#b76e79",
	"rose pink":                     "#ff66cc",
	"rose quartz":                   "#aa98a9",
	"rose taupe":                    "#905d5d",
	"rosewood":                      "#65000b",
	"rosso corsa":                   "#d40000",
	"rosy brown":                    "#bc8f8f",
	"royal azure":                   "#0038a8",
	"royal blue":                    "#002366",
	"royal fuchsia":                 "#ca2c92",
	"royal purple":                  "#7851a9",
	"ruby":                          "#e0115f",
	"ruddy":                         "#ff0028",
	"ruddy brown":                   "#bb6528",
	"ruddy pink":                    "#e18e96",
	"rufous":                        "#a81c07",
	"russet":                        "#80461b",
	"rust":                          "#b7410e",
	"sacramento state green":        "#00563f",
	"saddle brown":                  "#8b4513",
	"safety orange":                 "#ff6700",
	"saffron":                       "#f4c430",
	"salmon pink":                   "#ff91a4",
	"sandstorm":                     "#ecd540",
	"sandy brown":                   "#f4a460",
	"sangria":                       "#92000a",
	"sap green":                     "#507d2a",
	"sapphire":                      "#082567",
	"satin sheen gold":              "#cba135",
	"scarlet":                       "#ff2400",
	"school bus yellow":             "#ffd800",
	"screamin' green":               "#76ff7a",
	"sea green":                     "#2e8b57",
	"seal brown":                    "#321414",
	"selective yellow":              "#ffba00",
	"sepia":                         "#704214",
	"shadow":                        "#8a795d",
	"shamrock green":                "#009e60",
	"shocking pink":                 "#fc0fc0",
	"sinopia":                       "#cb410b",
	"skobeloff":                     "#007474",
	"sky blue":                      "#87ceeb",
	"sky magenta":                   "#cf71af",
	"slate blue":                    "#6a5acd",
	"slate gray":                    "#708090",
	"smokey topaz":                  "#933d41",
	"smoky black":                   "#100c08",
	"spiro disco ball":              "#0fc0fc",
	"splashed white":                "#fefdff",
	"spring bud":                    "#a7fc00",
	"steel blue":                    "#4682b4",
	"st. patrick's blue":            "#23297a",
	"straw":                         "#e4d96f",
	"sunglow":                       "#ffcc33",
	"tangelo":                       "#f94d00",
	"tangerine":                     "#f28500",
	"tangerine yellow":              "#ffcc00",
	"taupe gray":                    "#8b8589",
	"tea green":                     "#d0f0c0",
	"teal blue":                     "#367588",
	"teal green":                    "#006d5b",
	"tenné":                         "#cd5700",
	"terra cotta":                   "#e2725b",
	"thulian pink":                  "#de6fa1",
	"tickle me pink":                "#fc89ac",
	"tiffany blue":                  "#0abab5",
	"tiger's eye":                   "#e08d3c",
	"timberwolf":                    "#dbd7d2",
	"titanium yellow":               "#eee600",
	"toolbox":                       "#746cc0",
	"topaz":                         "#ffc87c",
	"tractor red":                   "#fd0e35",
	"tropical rain forest":          "#00755e",
	"true blue":                     "#0073cf",
	"tufts blue":                    "#417dc1",
	"tumbleweed":                    "#deaa88",
	"turkish rose":                  "#b57281",
	"turquoise blue":                "#00ffef",
	"turquoise green":               "#a0d6b4",
	"tuscan red":                    "#66424d",
	"twilight lavender":             "#8a496b",
	"tyrian purple":                 "#66023c",
	"ua blue":                       "#0033aa",
	"ua red":                        "#d9004c",
	"ube":                           "#8878c3",
	"ucla blue":                     "#536895",
	"ucla gold":                     "#ffb300",
	"ufo green":                     "#3cd070",
	"ultramarine":                   "#120a8f",
	"ultramarine blue":              "#4166f5",
	"ultra pink":                    "#ff6fff",
	"umber":                         "#635147",
	"united nations blue":           "#5b92e5",
	"university of california gold": "#b78727",
	"unmellow yellow":               "#ffff66",
	"up maroon":                     "#7b1113",
	"upsdell red":                   "#ae2029",
	"urobilin":                      "#e1ad21",
	"utah crimson":                  "#d3003f",
	"vegas gold":                    "#c5b358",
	"venetian red":                  "#c80815",
	"verdigris":                     "#43b3ae",
	"veronica":                      "#a020f0",
	"viridian":                      "#40826d",
	"vivid auburn":                  "#922724",
	"vivid burgundy":                "#9f1d35",
	"vivid cerise":                  "#da1d81",
	"vivid tangerine":               "#ffa089",
	"vivid violet":                  "#9f00ff",
	"warm black":                    "#004242",
	"wenge":                         "#645452",
	"white smoke":                   "#f5f5f5",
	"wild blue yonder":              "#a2add0",
	"wild strawberry":               "#ff43a4",
	"wild watermelon":               "#fc6c85",
	"wine":                          "#722f37",
	"wisteria":                      "#c9a0dc",
	"xanadu":                        "#738678",
	"yale blue":                     "#0f4d92",
	"yellow green":                  "#9acd32",
	"yellow orange":                 "#ffef02",
	"zaffre":                        "#0014a8",
	"zinnwaldite brown":             "#2c1608",
}
